[package]
name = "heillo"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
winapi = { version = "0.3", features = ["winuser", "wincon", "handleapi", "processenv"] }
